name: flutter_image_compress
description: Compress Pictures. Can effectively reduce the size of the transmission.
repository: https://github.com/fluttercandies/flutter_image_compress
version: 2.0.4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress_platform_interface: ^1.0.2
  flutter_image_compress_common: 
    git: 
      url: git@github.com:tatlacas/flutter_image_compress.git
      path: packages/flutter_image_compress_common
      ref: tat-dev
  flutter_image_compress_web: ^0.1.3+1

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_image_compress_common
      ios:
        default_package: flutter_image_compress_common
      web:
        default_package: flutter_image_compress_web